### PR TITLE
Payroll merged into master

### PR DESCRIPTION
**Pull request by CloCkWeRX**
See also #111 and #359 

This branch should be safe to one-click merge to master at all times, more or less.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Tests failing:
28afa6b5b6f20994daf06a2aff5607cdd29a635f is the first bad commit
commit 28afa6b5b6f20994daf06a2aff5607cdd29a635f
Author: Daniel O'Connor <daniel.oconnor@gmail.com>
Date:   Sat Apr 1 12:57:09 2017 +1000

    Merge

:040000 040000 715f1a186f7695172d8889b60d663701882d1bb7 5f84c67c5c1b2d41d685790effad8b37b14920e2 M	lib

**Comment by CloCkWeRX** [comment]
This looks very intimidating, but the main bits which are 'scary' compared to master are the has_one commits in the original payroll branch.

They break tests, and TBH, I think that the belongs_to relationship being an alias; which works well on master and has for some time; is probably a better way to go.

**Comment by CloCkWeRX** [comment]
@rjaus and everyone else... do we feel brave enough to pull the trigger on this for a 3.0.0 release candidate or similar?

**Comment by rjaus** [comment]
@CloCkWeRX I'm keen to see a major version release that includes payroll.  I'd like to get https://github.com/ghiculescu/xeroizer/tree/payroll merged in first, so we all continue forward together.

**Comment by rjaus** [comment]
@ghiculescu how much work, and what's your level of interest, in merging your payroll branch upstream?

**Comment by CloCkWeRX** [comment]
https://travis-ci.org/CloCkWeRX/xeroizer/builds/326639511 still happy

**Comment by CloCkWeRX** [comment]
I'm.... actually still keen to pull the trigger on this one and the major version bump. Potentially, we absorb @ghiculescu's work in for a 4.0 milestone? I don't want to lose it but at the same time it's been a few years forked; so the end users are forced to make a bit of a choice.

**Comment by rikkipitt** [comment]
@CloCkWeRX @rjaus Do you folks need any help on this? I'm keen on getting this merged in if you need me!

**Comment by CloCkWeRX** [comment]
Given we haven't made much progress in the past two years, going to create a stable 2.X branch and apply this.

**Pull request merged**
