### PR TITLE
Enable BankTransfer

### PR DESCRIPTION
**Pull request by mech**
Base on new BankTransfers API (still beta) at http://developer.xero.com/documentation/api/bank-transfers/

I have successfully imported it once.

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
Test coverage wouldn't hurt!

**Comment by mech** [comment]
Sorry about that, it is hard looking at the test and know where to begin. But I will try it.

**Comment by maxime-d** [comment]
:+1:

**Comment by CloCkWeRX** [comment]
Might be better to redo this as a fresh feature branch / cherry pick the relevant commits.

IE

```
git fetch waynerobinson master
git checkout waynerobinson/master
git checkout -b enable_bank_transfers
git cherry-pick 	cd34f06
git cherry-pick ...

git push -u origin enable_bank_transfers
```

**Comment by CloCkWeRX** [comment]
I'm going to close this in favour of #373

**Comment by mech** [comment]
Great as long as it is implemented 👍

**Pull request closed without merging**
