### PR TITLE
Add RepeatingInvoices

### PR DESCRIPTION
**Pull request by steveh**
This is a working starting point. Xero only supports fetching repeating invoices at this time.

I'm not familiar with how tests are supposed to be put together so let me know if you need something different.

### CODE REVIEW

**Comment by waynerobinson** [comment]
Thanks for the PR. Is it possible to convert this so that the RepeatingInvoice class is a sub-class of Invoice, or is there a reason why this doesn't make sense?

**Comment by steveh** [comment]
There are quite a few fields that are applicable to Invoices but not RepeatingInvoices. Also, it's not possible to GET a single RepeatingInvoice. I thought about making a module that includes common behaviour, but you hadn't done that for CreditNotes so wasn't sure if that was desired.

**Comment by steveh** [comment]
Also, there's no way to add/update RepeatingInvoices, so the validation logic is not required. Should it be taken out?

**Comment by waynerobinson** [comment]
No problem, its probably better to keep this like this then to main context.

Yes, the validation logic should probably be removed for now. Validation could be different for repeating invoices anyway.

**Comment by steveh** [comment]
OK, that's removed.

**Pull request merged**
