### PR TITLE
Removed duplicate builder v2.1.2 dependancies

### PR DESCRIPTION
**Pull request by ianbrown78**
Duplicate entries of builder v2.1.2 are causing 'gemspec is not valid' error during a deployment.

### CODE REVIEW

**Comment by waynerobinson** [comment]
Where is the duplicate? I only see a single builder dependency.

**Comment by ianbrown78** [comment]
In payroll branch gemspec. There is a duplicate builder v2.1.2 in each branch of the if-else.

**Comment by CloCkWeRX** [comment]
Ah @ianbrown78 we probably want to send this one into @ghiculescu's payroll branch; which is what we're using/where you got stuck.

**Comment by ghiculescu** [comment]
I'm working on merging master into payroll at the moment (taking a while - it's a big merge and I there's plenty to test) so when that's done this will be fixed.

**Comment by CloCkWeRX** [comment]
Is there anything we can do to help re big ugly merge? Keep starting the
process of diffing various branches to make one giant PR... Happy to write
tests,  etc.

**Comment by ghiculescu** [comment]
Yeah if you wanna have a crack at doing the merge I'm happy to review it. 

Alex Ghiculescu
alex@tanda.co

**Comment by ghiculescu** [comment]
I just pushed this: https://github.com/ghiculescu/xeroizer/commit/34be86cbce08741f5164d60feffe5e79fb70c5da

Seems like everything still works fine in my internal testing. Would suggest you do your own too @CloCkWeRX 

Let me know how you go!

**Pull request closed without merging**
