### PR TITLE
Add Discount and Website to Contacts

### LINKED ISSUE #347: Contact is missing website attribute
contact model doesn't have the website field

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fixes #347 #255  and #322  

For both https://developer.xero.com/documentation/api/contacts documents it, even if the api samples don't provide examples of it

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
@waynerobinson , if you get a bit could you look at/merge this one?

**Comment by waynerobinson** [comment]
👍

**Comment by CloCkWeRX** [comment]
Thanks! There's a few other one liners pending I think too

**Comment by waynerobinson** [comment]
By the way, I plan on spending some time over the weekend on various open PRs, etc here. So let me know if you have any questions.

Also, I think I'd like to add some extra people with commit bits. Are you interested @CloCkWeRX?

**Comment by CloCkWeRX** [comment]
Sure!

**Comment by waynerobinson** [comment]
Invite sent! 🍻

**Pull request merged**
