### PR TITLE
Use invoice line items returned with paged invoice results

### PR DESCRIPTION
**Pull request by pinfieldharm**
* Add option for associations downloaded with paged results. Use
the :complete_with_page flag on association.
* Also add DEBUG-level logging of server xml responses

(This is a resubmission, I messed up the previous branch with a forced update)

### CODE REVIEW

**Comment by cameronbourgeois** [comment]
Hi @pinfieldharm,

Nice work on this PR! I'm using this in my project :)

I did find one bug which was preventing your optimisations from running on page=0

See my branch fixing the issue here
https://github.com/TouchtechLtd/xeroizer/commit/a3106f603870b7477170de3cf30b669c5ccf72d0

Cheers!

**Comment by jamesknelson-misoca** [comment]
Would be wonderful if this could be merged, it seriously reduces the number of necessary API requests.

**Comment by cameronbourgeois** [comment]
@jamesknelson-misoca a big :+1: from me on that

**Comment by pinfieldharm** [comment]
Hi @cameronbourgeois I'll add your fix to the pull request and rebase it since its been like 6 months since I first submitted it.

**Comment by pinfieldharm** [comment]
@waynerobinson I've incorporated a change from @cameronbourgeois to my PR for paged invoice line items, originally submitted last October, and also rebased it with master. Would you kindly take a look at it when you have a chance?

**Comment by cameronbourgeois** [comment]
Cheers @waynerobinson :smiley:

**Comment by waynerobinson** [comment]
Thanks for this.

**Pull request merged**
