### PR TITLE
Payroll

### PR DESCRIPTION
**Pull request by layby42**
Hi,

pull request to payroll branch will have changes done by you and others to the master branch in May... quite messy
pull request to master branch is more compact - only October, but I'm not sure you are ready to get payroll into the main branch... up to you

### CODE REVIEW

**Comment by RustComet** [comment]
@layby42 Hey there. 

Trying to integrate with Xero Payroll now, and was wondering what the issues were that you came across in the end here? Any tips or tricks? What still needs to be done here to get this branch working?

**Comment by layby42** [comment]
Hi,

I do not work on apps that need integration with Xero anymore, so do not support syreclabs/xeroizer. The latest ruby vertion I've been working with is what you are trying to merge (https://github.com/syreclabs/xeroizer/tree/payroll), the functionality it provides was enough to handle business tasks my clients needed to handle. The goal was not to make perfect payroll, the goal was to wait somehow until payroll support added to official xeroizer gem.

If I correctly remember, the code does not cover whole payroll, not very accurate with validations and it is difficult to get exact errors (came from the original xeroizer). It most likely needs dependency and related code upgrade. 

>What still needs to be done here to get this branch working?

There still is at least one active rails app using payroll, so I suppose it should work as is.

**Comment by CloCkWeRX** [comment]
I made tiny bit of progress merging some of the harmless commits, but am unsure on 6ad7be4364e405a423cfc5d8d952cd4c273724bf

**Comment by CloCkWeRX** [comment]
Going to shift this to #359

**Pull request closed without merging**
