### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Travis CI makes keeping tests passing pretty simple, this PR adds support for it.

To enable it, simply visit http://travis-ci.org/ ; sign up, and enable the waynerobinson/xeroizer repo.

I'd recommend applying #181 just after this one to see it go from failing to passing.

### CODE REVIEW

**Comment by timdiggins** [comment]
@CloCkWeRX @waynerobinson this is such a great idea -- any reason why it has stalled?

**Comment by CloCkWeRX** [comment]
I think its just been overlooked a bit. Works really well on other projects I contribute to, still keen to add it

**Comment by CloCkWeRX** [comment]
Fingers crossed, this doesn't generate a billion build failure emails; but does let us know when a pull request isn't suitable to be merged.

**Comment by waynerobinson** [comment]
Probably will… the testing coverage leaves a bit to be desired. But it will be cool to get this working.

**Comment by timdiggins** [comment]
great news -- well done for getting this done @CloCkWeRX @waynerobinson

**Comment by timdiggins** [comment]
But think you need to enable it on travis https://travis-ci.org/waynerobinson/xeroizer @waynerobinson 

waynerobinson_xeroizer_-_travis_ci

**Pull request merged**
