### PR TITLE
Fix warnings: variables, not initialized or not set

### PR DESCRIPTION
**Pull request by CloCkWeRX**
This isn't all of them, but it makes things look a lot less like:
```
bundle exec rake test:unit
...
./home/clockwerx/xeroizer/lib/xeroizer/record/base_model.rb:100: warning: instance variable @allow_batch_operations not initialized
/home/clockwerx/xeroizer/lib/xeroizer/record/base_model.rb:100: warning: instance variable @allow_batch_operations not initialized
/home/clockwerx/xeroizer/lib/xeroizer/record/base_model.rb:100: warning: instance variable @allow_batch_operations not initialized
/home/clockwerx/xeroizer/lib/xeroizer/record/base_model.rb:100: warning: instance variable @allow_batch_operations not initialized
/home/clockwerx/xeroizer/lib/xeroizer/record/base_model.rb:100: warning: instance variable @allow_batch_operations not initialized
./home/clockwerx/xeroizer/lib/xeroizer/record/base_model.rb:100: warning: instance variable @allow_batch_operations not initialized
/home/clockwerx/xeroizer/lib/xeroizer/record/base_model.rb:100: warning: instance variable @allow_batch_operations not initialized
```

### CODE REVIEW

**Comment by tatey** [comment]
Appreciate you fixing these tests. I'm just in the process of making a patch and saw all the warnings :+1:

**Comment by CloCkWeRX** [comment]
Might need to have a think about the skip_writer or calculated changes; I added documentation but am not really sure if its enough.

It does prevent double method definition though.

**Comment by nnc** [comment]
Thank you for this pull request @CloCkWeRX. It's so great to see all this work being done on Xeroizer!

It may be easier and quicker for @waynerobinson to review and merge all these changes if you can split this into 3 pull request:

1. warning fixes and similar
2. model/association improvements
3. whitespace changes

**Comment by CloCkWeRX** [comment]
There's a lot here, so I will probably rework these on master directly in small batches.

**Comment by CloCkWeRX** [comment]
Have cherry-picked up to 	4d298a2
Redoing PR with the other stuff and merge conflicts sorted.

**Pull request closed without merging**
